"""
Default configuration values shared across CLI scripts.
"""

# Full active-learning loop defaults
REPETITION = 10
TARGET = 50
GENERATIONS = 50
POPULATION = 200
OUTPUT_DIR = "output"
LOG_LEVEL = "INFO"
IS_MOCK = False
ONLY_SUBMITTED = False
ML_CANDIDATE_POOL_SIZE = 50

# Training defaults
TRAIN_EPOCHS = 5
TRAIN_BATCH_SIZE = 32
TRAIN_LR = 1e-3
TRAIN_WEIGHT_DECAY = 1e-2
TRAIN_VAL_RATIO = 0.15
SEED = 42
MONITOR_GPU = True

# WorldQuant BRAIN simulation settings (requested schema)
# Fixed settings
SIM_TYPE = "REGULAR"
SIM_LANGUAGE = "FASTEXPR"
SIM_INSTRUMENT_TYPE = "EQUITY"
SIM_REGION = "USA"
SIM_DELAY = 1
SIM_UNIT_HANDLING = "VERIFY"

# Dropdown-like settings
SIM_UNIVERSE_CHOICES = ["TOP3000", "TOP1000", "TOP500", "TOP200", "TOPSP500"]
SIM_NEUTRALIZATION_CHOICES = ["NONE", "MARKET", "SECTOR", "INDUSTRY", "SUBINDUSTRY"]
SIM_PASTEURIZATION_CHOICES = ["ON", "OFF"]
SIM_NAN_HANDLING_CHOICES = ["ON", "OFF"]

# Defaults for tunable settings
SIM_DEFAULT_UNIVERSE = "TOP3000"
SIM_DEFAULT_NEUTRALIZATION = "SUBINDUSTRY"
SIM_DEFAULT_DECAY = 0
SIM_DEFAULT_TRUNCATION = 0.08
SIM_DEFAULT_PASTEURIZATION = "ON"
SIM_DEFAULT_NAN_HANDLING = "OFF"
SIM_DEFAULT_TEST_PERIOD = "P1Y"

# Pipeline rule thresholds aligned to BRAIN IS checks
MIN_SHARPE = 1.25
MIN_FITNESS = 1.0
MIN_RETURNS = 0.01
MIN_TURNOVER = 0.01
MAX_TURNOVER = 0.7
MAX_PAIRWISE_CORRELATION = 0.70

# Batch constraints
MAX_ALPHAS_PER_BATCH = 50
MAX_TOTAL_SUBMISSIONS = 500
MIN_SHARPE_FOR_BATCH = 1.25
MIN_FITNESS_FOR_BATCH = 1.0

# WQB rate-limit safety defaults
CONCURRENT_SIMULATIONS = 1
PRE_REQUEST_DELAY = 1.2
PRE_REQUEST_JITTER = 0.8

