from __future__ import annotations

import argparse
import os
from typing import Optional

from config import defaults
from modules.analytics.brain_rule_classifier import train_rule_classifier
from modules.analytics.gpu_monitor import start_nvidia_smi_logger


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Train a classifier for BRAIN IS testing pass/fail from expression tokens.")
    parser.add_argument("--dataset-csv", type=str, required=True, help="Dataset CSV generated by brain_ml_dataset_builder.py")
    parser.add_argument("--output-dir", type=str, required=True)
    parser.add_argument("--max-seq-len", type=int, default=256)
    parser.add_argument("--d-model", type=int, default=64)
    parser.add_argument("--nhead", type=int, default=4)
    parser.add_argument("--num-layers", type=int, default=2)
    parser.add_argument("--batch-size", type=int, default=defaults.TRAIN_BATCH_SIZE)
    parser.add_argument("--lr", type=float, default=defaults.TRAIN_LR)
    parser.add_argument("--weight-decay", type=float, default=defaults.TRAIN_WEIGHT_DECAY)
    parser.add_argument("--epochs", type=int, default=defaults.TRAIN_EPOCHS)
    parser.add_argument("--val-ratio", type=float, default=defaults.TRAIN_VAL_RATIO)
    parser.add_argument("--seed", type=int, default=defaults.SEED)
    parser.add_argument("--monitor-gpu", type=str, default="", help="If non-empty: write nvidia-smi log to this file path")
    args = parser.parse_args(argv)

    os.makedirs(args.output_dir, exist_ok=True)

    monitor_ctx = None
    if args.monitor_gpu:
        monitor_ctx = start_nvidia_smi_logger(args.monitor_gpu, interval_sec=1.0)
        # Manually enter so the background thread starts (we're not using `with` here).
        monitor_ctx.__enter__()

    try:
        model_path = train_rule_classifier(
            args.dataset_csv,
            output_dir=args.output_dir,
            max_seq_len=args.max_seq_len,
            d_model=args.d_model,
            nhead=args.nhead,
            num_layers=args.num_layers,
            batch_size=args.batch_size,
            lr=args.lr,
            weight_decay=args.weight_decay,
            epochs=args.epochs,
            val_ratio=args.val_ratio,
            seed=args.seed,
            monitor_gpu_log_path=args.monitor_gpu or None,
        )
        print(f"[train] saved model={model_path}")
    finally:
        if monitor_ctx is not None:
            monitor_ctx.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

